#!/usr/bin/env bash
set -e

port=3999

./node_modules/.bin/coffee ./test/server.coffee $port &>/dev/null &
pid=$!
trap "kill $pid" INT EXIT

phantom="./node_modules/.bin/phantomjs"

[ -z "$CI" ] || echo "PhantomJS $($phantom -v)"

exec ./node_modules/.bin/mocha-phantomjs -p "$phantom" \
  "http://localhost:${port}/test/index.html"
